config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: ("lists#index")
  resources :lists, only: [:show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create, :show]
  end
  resources :bookmarks, only: [:destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
require 'json'
require 'net/http'
require 'uri'

class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @new_movie = movie_api(params[:bookmark][:search])
    @movie = Movie.new(
      title: @new_movie['title'],
      overview: @new_movie['overview'],
      poster_url: "https://image.tmdb.org/t/p/original/#{@new_movie['poster_path']}",
      rating: @new_movie['vote_average']
    )
    @movie.save

    @bookmark.movie_id = @movie.id
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id, :search)
  end
end

def movie_api(user_input)
  p = URI::Parser.new
  search = p.escape(user_input)
  url = URI("https://api.themoviedb.org/3/search/movie?query=#{search}&language=fr")

  http = Net::HTTP.new(url.host, url.port)
  http.use_ssl = true

  request = Net::HTTP::Get.new(url)
  request['accept'] = 'application/json'
  request['Authorization'] = 'Bearer TMBD_KEY'

  response = http.request(request)
  movies = JSON.parse(response.read_body)
  movies['results'][0]
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <div class="container text-center">
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :picture_url %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.gqmagazine.fr/photos/603e6a8da9360b0585bcbc6a/16:9/w_2560%2Cc_limit/108387402);">
    <h1>Listy</h1>
    <p>Stop to forget your movies</p>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add a new list
    </button>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5 text-secondary" id="exampleModalLabel">New List</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= simple_form_for(@list) do |f| %>
                  <%= f.input :name %>
                  <%= f.input :picture_url %>
                  </div>
                    <div class="modal-footer">
                    <%= f.submit "Add a list", class:"btn" %>
                   </div>
              <% end %>
          </div>
        </div>
      </div>
</div>



<div class="cards mt-5">
  <% @lists.each do |list| %>
    <div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.picture_url %>)">
    <%= link_to list.name, list_path(list), class:"a" %>
    </div>
    <%= link_to "Delete", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn--secondary" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render"form", list: @list%>

app/views/lists/show.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.picture_url  %>);">
<h1 class="m-5"><%= @list.name %></h1>
</div>


<!-- Button trigger modal -->
<button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#bookmarkModal">
  Add new bookmark
</button>

<!-- Modal -->
<div class="modal fade" id="bookmarkModal" tabindex="-1" aria-labelledby="bookmarkModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="bookmarkModalLabel">New bookmark</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark], html: { data: { controller: 'search', action: 'input->search#searching' } } do |f| %>
          <%= f.input :comment %>
          <%= f.input :search, input_html: { data: { search_target: 'input' }}%>
            <div data-search-target = "result" role="listbox">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.button :submit %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--Movie Card-->
<div class="container" style="text-align: center;">
<div class="card-wrapper mt-4">
<% @bookmarks.each do |bookmark|%>
  <div class="card-movie">
    <div class="card-front">
      <img src= <%= bookmark.movie.poster_url %> alt=<%= bookmark.movie.title %>/>
    </div>
      <div class="card-back">
        <h3> <%= bookmark.movie.title %></h3>
        <p><%= bookmark.movie.overview%></p>
        <p>Rating: <%= bookmark.movie.rating %>/10</p>
        <p> "<%= bookmark.comment %>"</p>
        <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn--secondary" %>
      </div>
  </div>
<% end %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <i class="fa-solid fa-film"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create a list",new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>